import Link from "next/link"
import { fetchAgentRuns, fetchRepositories } from "@/lib/api"
import { CheckCircle2, GitPullRequest, GitBranch, PlayCircle, Star } from "lucide-react"

export default async function DemoModePage() {
  let completedRuns: any[] = []
  let repos: any[] = []

  try {
    const [runList, repoList] = await Promise.all([
      fetchAgentRuns({ limit: 100 }),
      fetchRepositories(),
    ])
    // The type `AgentRunOut` is not directly exported in `AgentRunListOut` correctly in the TS here? 
    // Wait, let me cast it properly just in case.
    completedRuns = runList.runs.filter((r: any) => r.status === "completed" || (r.result?.pull_request_url != null))
    repos = repoList
  } catch {
    // API not reachable
  }

  const repoNames = new Map(repos.map((r: any) => [r.id, r.full_name]))

  return (
    <div className="max-w-5xl mx-auto py-8 space-y-8">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-semibold text-white tracking-tight flex items-center gap-3">
            <Star className="h-8 w-8 text-amber-400 fill-amber-400/20" />
            Demo Showcase
          </h1>
          <p className="mt-2 text-neutral-400">
            A curated view of successful autonomous executions. Real PRs generated by Forge.
          </p>
        </div>
      </div>

      {completedRuns.length === 0 ? (
        <div className="flex flex-col items-center justify-center p-12 rounded-xl border border-neutral-800 bg-neutral-900/30 border-dashed">
          <PlayCircle className="h-10 w-10 text-neutral-600 mb-4" />
          <p className="text-neutral-300 font-medium">No completed runs yet</p>
          <p className="mt-1 text-sm text-neutral-500">
            Run an agent on an issue to see it appear in the showcase.
          </p>
        </div>
      ) : (
        <div className="grid gap-6">
          {completedRuns.map((run: any) => {
            const repoName = repoNames.get(run.repository_id) ?? "Unknown Repository"
            const issueTitle = (run.result?.selected_issue as any)?.title || "Autonomous Update"
            
            return (
              <Link 
                key={run.id} 
                href={`/agents/${run.id}`}
                className="group flex flex-col sm:flex-row sm:items-center justify-between p-6 rounded-2xl border border-neutral-800 bg-[#0f0f0f] hover:bg-neutral-900 hover:border-neutral-700 transition-all duration-300 shadow-xl shadow-black/50"
              >
                <div className="flex items-center gap-6">
                  <div className="flex items-center justify-center bg-green-500/10 rounded-full h-14 w-14 border border-green-500/20 shadow-[0_0_15px_rgba(34,197,94,0.2)]">
                    <CheckCircle2 className="h-7 w-7 text-green-500" />
                  </div>
                  <div>
                    <h3 className="text-lg font-semibold text-white group-hover:text-blue-400 transition-colors">
                      {issueTitle}
                    </h3>
                    <div className="flex items-center gap-3 mt-2 text-sm text-neutral-500">
                      <span className="font-mono flex items-center gap-1.5"><GitBranch className="h-3.5 w-3.5" />{repoName}</span>
                      <span>•</span>
                      <span className="text-neutral-400 flex items-center gap-1.5">
                        <GitPullRequest className="h-3.5 w-3.5" />
                        PR Created
                      </span>
                    </div>
                  </div>
                </div>

                <div className="mt-4 sm:mt-0">
                  <div className="px-4 py-2 rounded-lg bg-neutral-900 border border-neutral-800 text-sm font-medium text-neutral-300 group-hover:bg-neutral-800 group-hover:text-white transition-colors">
                    View Execution →
                  </div>
                </div>
              </Link>
            )
          })}
        </div>
      )}
    </div>
  )
}
