"""PR Generator agent for Sentinel Brain.

Synthesizes all previous reasoning stages into a high-quality
Pull Request draft that a human engineer could review and merge.

Design:
    - Pure LLM class; acts as an autonomous release coordinator.
    - Consumes all state from the pipeline (Plan, Validation, Tests, Review, etc).
    - Uses deterministic logic for branch naming and base branch selection.
    - Produces a strictly structured Markdown body.
    - Parses output directly into the existing :class:`PullRequestDraft` model.
    - Includes a deterministic heuristic fallback if the LLM is unavailable.
"""

from __future__ import annotations

import json
import logging
import re
from typing import TYPE_CHECKING, Any

from forge_workflows.state import (
    CodeChange,
    Plan,
    PullRequestDraft,
    RepoContext,
    Review,
    SelectedIssue,
    TestResult,
    ValidationResult,
)

if TYPE_CHECKING:
    from langchain_core.language_models import BaseChatModel

logger = logging.getLogger(__name__)


class PRGeneratorAgent:
    """Evaluates the entire pipeline output and drafts a Pull Request.

    Args:
        llm: A LangChain chat model instance (e.g. ``ChatGoogleGenerativeAI``).
    """

    name: str = "pr_generator"

    def __init__(self, llm: BaseChatModel) -> None:
        self._llm = llm

    async def generate_pr(
        self,
        *,
        code_changes: list[CodeChange],
        plan: Plan,
        selected_issue: SelectedIssue,
        repo_context: RepoContext,
        validation_result: ValidationResult | None,
        test_results: list[TestResult],
        review: Review | None,
    ) -> PullRequestDraft:
        """Synthesize all engineering evidence into a PullRequestDraft.

        Args:
            code_changes: The patches generated by the DeveloperAgent.
            plan: The implementation plan guiding the work.
            selected_issue: The issue being resolved.
            repo_context: Repository understanding.
            validation_result: Validation findings.
            test_results: Simulated test verification results.
            review: Senior review feedback.

        Returns:
            A :class:`PullRequestDraft` instance with title, body, and branches.
        """
        logger.info(
            "Drafting PR for issue #%d: %s",
            selected_issue.number,
            selected_issue.title,
        )

        # 1. Deterministic Branch Names
        slug = re.sub(r'[^a-z0-9]+', '-', selected_issue.title.lower()).strip('-')
        issue_type = "feature"
        
        # Determine issue type from fallback to title
        if "bug" in selected_issue.title.lower() or "fix" in selected_issue.title.lower():
            issue_type = "fix"
            
        branch_name = f"{issue_type}/issue-{selected_issue.number}-{slug}"
        base_branch = "main"
        if repo_context and hasattr(repo_context, "default_branch") and getattr(repo_context, "default_branch"):
            base_branch = getattr(repo_context, "default_branch")

        if not code_changes:
            logger.warning("No code changes provided to PR Generator")
            return self._fallback_generate(
                branch_name, base_branch, selected_issue, code_changes, plan, validation_result, test_results, review
            )

        prompt = self._build_prompt(
            code_changes, plan, selected_issue, validation_result, test_results, review
        )

        try:
            response = await self._llm.ainvoke(prompt)
            content = response.content if hasattr(response, "content") else str(response)
            parsed = self._parse_llm_response(content)
            
            draft = self._build_draft(parsed, branch_name, base_branch)
            logger.info("Generated PR draft successfully: %s", draft.title)
            return draft
        except Exception:
            logger.exception("LLM PR generation failed — using heuristic fallback")
            return self._fallback_generate(
                branch_name, base_branch, selected_issue, code_changes, plan, validation_result, test_results, review
            )

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _build_prompt(
        self,
        changes: list[CodeChange],
        plan: Plan,
        issue: SelectedIssue,
        validation: ValidationResult | None,
        tests: list[TestResult],
        review: Review | None,
    ) -> str:
        """Construct the PR generation prompt for the LLM."""

        # Context block
        context_block = (
            f"Issue #{issue.number}: {issue.title}\n"
            f"Issue Description: {issue.body or '(none)'}\n\n"
            f"Planner Approach: {plan.approach_reasoning}\n"
        )
        
        # Code changes summary
        changes_block = ""
        for c in changes:
            changes_block += (
                f"  - File: {c.file_path}\n"
                f"    Description: {c.description}\n"
            )

        # Validation Result
        val_block = "Passed: False\nIssues: None\n"
        val_passed = False
        if validation:
            val_passed = validation.passed
            val_block = (
                f"Passed: {validation.passed}\n"
                f"Issues: {validation.issues}\n"
            )

        # Test Results
        test_block = ""
        tests_passed = True
        if not tests:
            test_block = "None\n"
        else:
            for t in tests:
                test_block += f"  - {t.name} (Passed: {t.passed})\n"
                if not t.passed:
                    tests_passed = False

        # Review
        review_block = "Approved: False\nComments: None\nSecurity Issues: None\n"
        rev_approved = False
        if review:
            rev_approved = review.approved
            review_block = (
                f"Approved: {review.approved}\n"
                f"Comments: {review.comments}\n"
                f"Security Issues: {review.security_issues}\n"
            )
            
        # Recommendation Logic
        recommendation = "Safe to merge. Validation passed, tests passed, reviewer approved, no security concerns."
        if not val_passed or not tests_passed or not rev_approved:
            recommendation = "Do not merge. "
            if not val_passed:
                recommendation += "Validation failed. "
            if not tests_passed:
                recommendation += "Tests failed. "
            if not rev_approved:
                recommendation += "Reviewer rejected. Additional development required."

        return f"""You are a senior release coordinator summarizing an AI-generated patch into a Pull Request.

{context_block}

Code Changes:
{changes_block}

Validation Results:
{val_block}

Test Results:
{test_block}

Review Results:
{review_block}

PR Requirements:
1. Title: Provide a professional PR title (e.g., "Fix: Change text color to red").
2. Body: You MUST output a JSON object with exactly the fields "title" and "body". The "body" string MUST follow this EXACT markdown structure, with these EXACT headers:

## Summary
[Write a concise summary of what this PR does and why]

## Changes
[List the modified files and a brief summary of the patch]

## Validation
[Indicate if validation passed or failed, and list any key issues]

## Testing
[List the simulated tests that were verified and their status]

## Review
[Summarize the reviewer's approval status and confidence level. You MUST include the exact confidence text from the reviewer comments if present, e.g., "Confidence: High"]

## Security
[List security concerns explicitly. If none, write "No security concerns identified."]

## Risk Assessment
[Write a short assessment of the risk level (Low/Medium/High) and why]

## Merge Recommendation
{recommendation}

Respond with valid JSON only. No markdown fences around the JSON, just the JSON object with "title" and "body" keys."""

    @staticmethod
    def _parse_llm_response(content: str) -> dict[str, str]:
        """Extract a JSON object from the LLM response."""
        text = content.strip()

        # Strip markdown code fences
        fence_match = re.search(r"```(?:json)?\s*\n?(.*?)```", text, re.DOTALL)
        if fence_match:
            text = fence_match.group(1).strip()

        try:
            parsed = json.loads(text)
            if isinstance(parsed, dict) and "title" in parsed and "body" in parsed:
                return {"title": str(parsed["title"]), "body": str(parsed["body"])}
            logger.warning("LLM returned unexpected JSON structure")
            return {}
        except json.JSONDecodeError as exc:
            logger.warning("Failed to parse LLM JSON response: %s", exc)
            return {}

    def _build_draft(self, parsed: dict[str, str], branch: str, base_branch: str) -> PullRequestDraft:
        """Build a PullRequestDraft object."""
        title = parsed.get("title", "Automated Pull Request")
        body = parsed.get("body", "No description provided.")

        return PullRequestDraft(
            title=title,
            body=body,
            branch=branch,
            base_branch=base_branch,
        )

    def _fallback_generate(
        self,
        branch: str,
        base_branch: str,
        issue: SelectedIssue,
        changes: list[CodeChange],
        plan: Plan,
        validation: ValidationResult | None,
        tests: list[TestResult],
        review: Review | None,
    ) -> PullRequestDraft:
        """Deterministic heuristic fallback when LLM is unavailable."""
        title = f"Fix: Resolve issue #{issue.number} - {issue.title}"
        
        # Summary
        summary = f"Resolves issue #{issue.number} by following the approved plan:\n> {plan.approach_reasoning}"
        
        # Changes
        changes_md = ""
        for c in changes:
            changes_md += f"- `{c.file_path}`: {c.description}\n"
        if not changes_md:
            changes_md = "No changes provided.\n"
            
        # Validation
        val_passed = validation is not None and validation.passed
        val_md = f"✓ Passed" if val_passed else f"❌ Failed\n"
        if validation and validation.issues:
            val_md += "\nIssues:\n" + "\n".join(f"- {i}" for i in validation.issues)
            
        # Testing
        test_md = ""
        tests_passed = True
        if not tests:
            test_md = "No tests generated.\n"
        else:
            for t in tests:
                status = "✓" if t.passed else "❌"
                test_md += f"{status} {t.name}\n"
                if not t.passed:
                    tests_passed = False
                    
        # Review & Security
        rev_approved = review is not None and review.approved
        rev_md = f"✓ Approved" if rev_approved else f"❌ Rejected"
        sec_md = "No security concerns identified."
        
        if review:
            for c in review.comments:
                if c.startswith("Confidence:"):
                    rev_md += f"\n{c.split('.')[0]}"
            if review.security_issues:
                sec_md = "\n".join(f"- {s}" for s in review.security_issues)
                
        # Risk Assessment
        risk_md = "Low.\nOnly intended files were modified."
        if not tests_passed or not val_passed:
            risk_md = "High.\nValidation or tests failed."
            
        # Merge Recommendation
        if val_passed and tests_passed and rev_approved:
            rec_md = "Safe to merge. Validation passed, tests passed, reviewer approved, no security concerns."
        else:
            rec_md = "Do not merge. "
            if not val_passed: rec_md += "Validation failed. "
            if not tests_passed: rec_md += "Tests failed. "
            if not rev_approved: rec_md += "Reviewer rejected. Additional development required."

        body = f"""## Summary
{summary}

## Changes
{changes_md}
## Validation
{val_md}

## Testing
{test_md}
## Review
{rev_md}

## Security
{sec_md}

## Risk Assessment
{risk_md}

## Merge Recommendation
{rec_md}
"""

        return PullRequestDraft(
            title=title,
            body=body,
            branch=branch,
            base_branch=base_branch,
        )
