"""Reviewer agent for Sentinel Brain.

Performs a holistic code review mimicking a senior software engineer.
Evaluates code changes based on validation results, test outputs,
alignment with the planner's strategy, and security concerns.

Design:
    - Pure LLM class; acts as an intelligent PR reviewer.
    - Consumes Plan, CodeChanges, ValidationResult, and TestResults.
    - Embeds a qualitative confidence level in comments.
    - Proactively identifies security issues.
    - Parses output directly into the existing :class:`Review` model.
    - Includes a deterministic heuristic fallback if the LLM is unavailable.
"""

from __future__ import annotations

import json
import logging
import re
from typing import TYPE_CHECKING, Any

from forge_workflows.state import (
    CodeChange,
    Plan,
    RepoContext,
    Review,
    SelectedIssue,
    TestResult,
    ValidationResult,
)

if TYPE_CHECKING:
    from langchain_core.language_models import BaseChatModel

logger = logging.getLogger(__name__)


class ReviewerAgent:
    """Evaluates the entire generated patch and decides on approval.

    Args:
        llm: A LangChain chat model instance (e.g. ``ChatGoogleGenerativeAI``).
    """

    name: str = "reviewer"

    def __init__(self, llm: BaseChatModel) -> None:
        self._llm = llm

    async def review(
        self,
        *,
        code_changes: list[CodeChange],
        plan: Plan,
        selected_issue: SelectedIssue,
        repo_context: RepoContext,
        validation_result: ValidationResult | None,
        test_results: list[TestResult],
    ) -> Review:
        """Perform a senior-level code review of the proposed patch.

        Args:
            code_changes: The patches generated by the DeveloperAgent.
            plan: The implementation plan guiding the work.
            selected_issue: The issue being resolved.
            repo_context: Repository understanding.
            validation_result: Validation findings.
            test_results: Simulated test verification results.

        Returns:
            A :class:`Review` instance indicating approval or rejection,
            along with comments, security findings, and suggestions.
        """
        logger.info(
            "Reviewing patch for issue #%d: %s",
            selected_issue.number,
            selected_issue.title,
        )

        if not code_changes:
            logger.warning("No code changes provided to Reviewer")
            return Review(
                approved=False,
                comments=["Confidence: Low. No code changes were submitted for review."],
                security_issues=[],
                suggestions=["Regenerate focused code changes via the Developer node."],
            )

        prompt = self._build_prompt(
            code_changes, plan, selected_issue, repo_context, validation_result, test_results
        )

        try:
            response = await self._llm.ainvoke(prompt)
            content = response.content if hasattr(response, "content") else str(response)
            parsed = self._parse_llm_response(content)
            review_obj = self._build_review(parsed)
            
            logger.info(
                "Review completed: %s (Confidence: %s)",
                "APPROVED" if review_obj.approved else "REJECTED",
                "Assessed in comments"
            )
            return review_obj
        except Exception:
            logger.exception("LLM review generation failed — using heuristic fallback")
            return self._fallback_review(code_changes, plan, validation_result, test_results)

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _build_prompt(
        self,
        changes: list[CodeChange],
        plan: Plan,
        issue: SelectedIssue,
        repo_context: RepoContext,
        validation: ValidationResult | None,
        tests: list[TestResult],
    ) -> str:
        """Construct the review prompt for the LLM."""

        # Context block
        context_block = (
            f"Repository: {repo_context.repository_name}\n"
            f"Languages: {', '.join(repo_context.languages) or 'Unknown'}\n\n"
            f"Issue #{issue.number}: {issue.title}\n"
            f"Issue Description: {issue.body or '(none)'}\n\n"
            f"Planner Approach: {plan.approach_reasoning}\n"
        )
        
        # Code changes
        changes_block = ""
        for i, c in enumerate(changes, 1):
            changes_block += (
                f"  Change {i}:\n"
                f"    File: {c.file_path}\n"
                f"    Description: {c.description}\n"
                f"    Patch:\n{c.patch}\n\n"
            )

        # Validation Result
        val_block = "None"
        if validation:
            val_block = (
                f"Passed: {validation.passed}\n"
                f"Issues: {validation.issues}\n"
                f"Suggestions: {validation.suggestions}\n"
            )

        # Test Results
        test_block = ""
        if not tests:
            test_block = "None\n"
        for t in tests:
            test_block += (
                f"  Test: {t.name}\n"
                f"  Passed: {t.passed}\n"
                f"  Output: {t.output}\n"
                f"  Error: {t.error or 'None'}\n\n"
            )

        return f"""You are a senior software engineer conducting a strict pull request review for an AI-generated patch.

{context_block}

Proposed Code Changes:
{changes_block}

Validation Results:
{val_block}

Test Results:
{test_block}

Review Guidelines:
1. You must decide whether to APPROVE or REJECT the patch.
2. Evidence Hierarchy: Base your decision on ValidationResults -> TestResults -> Planner alignment -> CodeChange scope -> Security findings.
3. Security: Proactively identify risks (hardcoded credentials, unsafe dependencies, auth/authorization modifications, removal of safeguards). If benign, return an empty security_issues list.
4. Confidence: Embed qualitative confidence levels inside your comments (Confidence: High, Confidence: Medium, Confidence: Low).
5. Justification: Provide technically meaningful comments. Do NOT use generic terms like "LGTM".
6. Actionability: If rejecting, provide highly actionable suggestions (e.g., "Remove unrelated modifications", "Regenerate focused code changes", "Expand regression testing").

Respond with a JSON object containing exactly these fields:

- "approved": boolean. True if the patch should merge, False if it needs revision.
- "comments": list of strings. Your review feedback. The very first comment MUST begin with "Confidence: [High|Medium|Low]." followed by evidence-backed justification.
- "security_issues": list of strings. Specific security concerns, if any.
- "suggestions": list of strings. Actionable steps for the developer if rejected, or minor post-merge notes if approved.

Respond with valid JSON only. No markdown, no explanation, just the JSON object."""

    @staticmethod
    def _parse_llm_response(content: str) -> dict[str, Any]:
        """Extract a JSON object from the LLM response."""
        text = content.strip()

        # Strip markdown code fences
        fence_match = re.search(r"```(?:json)?\s*\n?(.*?)```", text, re.DOTALL)
        if fence_match:
            text = fence_match.group(1).strip()

        try:
            parsed = json.loads(text)
            if isinstance(parsed, dict):
                return parsed
            logger.warning("LLM returned unexpected JSON type: %s", type(parsed))
            return {}
        except json.JSONDecodeError as exc:
            logger.warning("Failed to parse LLM JSON response: %s", exc)
            logger.debug("Raw LLM output: %s", content[:500])
            return {}

    @staticmethod
    def _build_review(parsed: dict[str, Any]) -> Review:
        """Build a Review object from the parsed LLM response."""
        approved = bool(parsed.get("approved", False))
        comments = parsed.get("comments", [])
        security_issues = parsed.get("security_issues", [])
        suggestions = parsed.get("suggestions", [])

        if not isinstance(comments, list):
            comments = [str(comments)]
        if not isinstance(security_issues, list):
            security_issues = [str(security_issues)]
        if not isinstance(suggestions, list):
            suggestions = [str(suggestions)]

        return Review(
            approved=approved,
            comments=[str(c) for c in comments],
            security_issues=[str(s) for s in security_issues],
            suggestions=[str(s) for s in suggestions],
        )

    @staticmethod
    def _fallback_review(
        changes: list[CodeChange],
        plan: Plan,
        validation: ValidationResult | None,
        tests: list[TestResult],
    ) -> Review:
        """Deterministic heuristic fallback when LLM is unavailable."""
        
        # Approval priority heuristics
        val_passed = validation is not None and validation.passed
        tests_passed = len(tests) > 0 and all(t.passed for t in tests)
        planned_files = set(plan.affected_files)
        changed_files = {c.file_path for c in changes}
        scope_ok = changed_files.issubset(planned_files)

        approved = val_passed and tests_passed and scope_ok

        comments = []
        suggestions = []
        security_issues = []

        if approved:
            confidence = "High" if val_passed and tests_passed else "Medium"
            comments.append(f"Confidence: {confidence}. The proposed change is minimal, aligns with the implementation plan, and is fully supported by validation and testing evidence. Approved.")
            suggestions.append("Proceed to PR generation.")
        else:
            confidence = "Low"
            comments.append(f"Confidence: {confidence}. The patch is rejected based on automated heuristic review.")
            
            if not val_passed:
                comments.append("Validation failed prior to review.")
                suggestions.append("Address all validation issues and regenerate code changes.")
            if not tests_passed:
                comments.append("One or more tests failed during simulated verification.")
                suggestions.append("Expand regression testing or fix failing tests.")
            if not scope_ok:
                comments.append(f"Scope violation: Modified files ({changed_files}) exceed planned scope ({planned_files}).")
                suggestions.append("Remove unrelated modifications and regenerate focused code changes.")
                
            # Heuristic security check
            for c in changes:
                if any(kw in c.patch.lower() for kw in ["password", "secret", "token", "key"]):
                    security_issues.append(f"Potential hardcoded credentials detected in {c.file_path}.")

        return Review(
            approved=approved,
            comments=comments,
            security_issues=security_issues,
            suggestions=suggestions,
        )
