"""Test agent for Sentinel Brain.

Simulates intelligent verification of the proposed code changes.
The agent acts as a QA engineer, evaluating what tests are necessary
to ensure confidence in the patch, prioritizing tests requested by
the Planner, and performing qualitative risk assessment.

Design:
    - Pure LLM class; does not execute actual tests or mutate state.
    - Consumes Plan, CodeChanges, and ValidationResult.
    - Enforces Planner -> Test alignment.
    - Embeds risk categorization (Low/Medium/High) within the output details.
    - Parses output directly into a list of :class:`TestResult`.
    - Includes a deterministic fallback for LLM unavailability.
"""

from __future__ import annotations

import json
import logging
import re
from typing import TYPE_CHECKING, Any

from forge_workflows.state import (
    CodeChange,
    Plan,
    RepoContext,
    SelectedIssue,
    TestResult,
    ValidationResult,
)

if TYPE_CHECKING:
    from langchain_core.language_models import BaseChatModel

logger = logging.getLogger(__name__)


class TestAgent:
    """Evaluates code changes and produces simulated test verification results.

    Args:
        llm: A LangChain chat model instance (e.g. ``ChatGoogleGenerativeAI``).
    """

    name: str = "test_agent"

    def __init__(self, llm: BaseChatModel) -> None:
        self._llm = llm

    async def test(
        self,
        *,
        code_changes: list[CodeChange],
        plan: Plan,
        selected_issue: SelectedIssue,
        repo_context: RepoContext,
        validation_result: ValidationResult | None,
    ) -> list[TestResult]:
        """Generate simulated test cases for the proposed code changes.

        Args:
            code_changes: The patches generated by the DeveloperAgent.
            plan: The implementation plan, containing requested tests.
            selected_issue: The issue being resolved.
            repo_context: Repository understanding.
            validation_result: Validation findings (if any).

        Returns:
            A list of :class:`TestResult` instances representing the verification.
        """
        logger.info(
            "Generating simulated tests for issue #%d: %s",
            selected_issue.number,
            selected_issue.title,
        )

        if not code_changes:
            logger.warning("No code changes provided to TestAgent")
            return [
                TestResult(
                    name="System Validation",
                    passed=False,
                    output="Risk: High. No code changes were provided to verify.",
                    error="Empty patch set",
                )
            ]

        prompt = self._build_prompt(
            code_changes, plan, selected_issue, repo_context, validation_result
        )

        try:
            response = await self._llm.ainvoke(prompt)
            content = response.content if hasattr(response, "content") else str(response)
            parsed = self._parse_llm_response(content)
            results = self._build_test_results(parsed)
            
            logger.info("Generated %d simulated test results", len(results))
            return results
        except Exception:
            logger.exception("LLM test generation failed — using heuristic fallback")
            return self._fallback_test(code_changes, plan, validation_result)

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _build_prompt(
        self,
        changes: list[CodeChange],
        plan: Plan,
        issue: SelectedIssue,
        repo_context: RepoContext,
        validation: ValidationResult | None,
    ) -> str:
        """Construct the test generation prompt for the LLM."""

        # Issue and Planner context
        context_block = (
            f"Repository: {repo_context.repository_name}\n"
            f"Languages: {', '.join(repo_context.languages) or 'Unknown'}\n\n"
            f"Issue #{issue.number}: {issue.title}\n"
            f"Planner Approach: {plan.approach_reasoning}\n"
        )
        
        # Tests requested by Planner
        # Fallback to empty string if tests_needed doesn't exist on plan
        tests_needed = getattr(plan, "tests_needed", [])
        if tests_needed:
            context_block += "Tests requested by Planner:\n"
            for t in tests_needed:
                context_block += f"  - {t}\n"
        else:
            context_block += "Tests requested by Planner: None explicitly stated.\n"

        # Code changes
        changes_block = ""
        for i, c in enumerate(changes, 1):
            changes_block += (
                f"  Change {i}:\n"
                f"    File: {c.file_path}\n"
                f"    Description: {c.description}\n"
                f"    Patch:\n{c.patch}\n\n"
            )

        # Validation Result
        val_block = "None"
        if validation:
            val_block = (
                f"Passed: {validation.passed}\n"
                f"Issues: {validation.issues}\n"
                f"Suggestions: {validation.suggestions}\n"
            )

        return f"""You are a senior QA engineer simulating the verification of AI-generated code changes.

Your job is to determine what tests are necessary to ensure confidence in the patch, run a simulated verification in your mind, and produce realistic test outputs.

{context_block}

Proposed Code Changes:
{changes_block}

Previous Validation Result:
{val_block}

Testing Guidelines:
1. ENFORCE PLANNER ALIGNMENT: You MUST include tests for every item listed under 'Tests requested by Planner'.
2. RISK ASSESSMENT: Every test output MUST begin with a qualitative risk assessment (Risk: Low, Risk: Medium, or Risk: High).
3. REGRESSION CHECKS: Generate minimal checks for UI/cosmetic changes. Expand coverage if multiple files or config files are modified. If there are validation warnings, increase scrutiny.
4. If a patch looks dangerous or introduces unrelated changes, simulate a failing test for it.

Respond with a JSON object containing a "tests" array. Each item in the array must have exactly these fields:

- "name": string. The test name or identifier (e.g., "Verify text color updated").
- "passed": boolean. Whether the simulated test passed.
- "output": string. The detailed output of the test. MUST start with the Risk assessment (e.g. "Risk: Low. The h1 color property changed..."). If you added a test not in the planner, explain why here.
- "error": string or null. If passed is false, explain the failure.

Respond with valid JSON only. No markdown, no explanation, just the JSON object."""

    @staticmethod
    def _parse_llm_response(content: str) -> dict[str, Any]:
        """Extract a JSON object from the LLM response."""
        text = content.strip()

        # Strip markdown code fences
        fence_match = re.search(r"```(?:json)?\s*\n?(.*?)```", text, re.DOTALL)
        if fence_match:
            text = fence_match.group(1).strip()

        try:
            parsed = json.loads(text)
            if isinstance(parsed, dict):
                return parsed
            logger.warning("LLM returned unexpected JSON type: %s", type(parsed))
            return {}
        except json.JSONDecodeError as exc:
            logger.warning("Failed to parse LLM JSON response: %s", exc)
            logger.debug("Raw LLM output: %s", content[:500])
            return {}

    @staticmethod
    def _build_test_results(parsed: dict[str, Any]) -> list[TestResult]:
        """Build TestResult objects from the parsed LLM response."""
        tests_data = parsed.get("tests", [])
        if not isinstance(tests_data, list):
            logger.warning("Expected 'tests' to be a list, got %s", type(tests_data))
            return []

        results = []
        for t in tests_data:
            if not isinstance(t, dict):
                continue
                
            name = str(t.get("name", "Unnamed Test"))
            passed = bool(t.get("passed", False))
            output = str(t.get("output", ""))
            error = t.get("error")
            if error is not None:
                error = str(error)
                
            results.append(
                TestResult(
                    name=name,
                    passed=passed,
                    output=output,
                    error=error,
                )
            )

        return results

    @staticmethod
    def _fallback_test(
        changes: list[CodeChange],
        plan: Plan,
        validation: ValidationResult | None,
    ) -> list[TestResult]:
        """Deterministic heuristic fallback when LLM is unavailable."""
        results: list[TestResult] = []
        
        # Base risk on number of files and validation
        risk_level = "Low"
        if len(changes) > 2:
            risk_level = "Medium"
        if validation and not validation.passed:
            risk_level = "High"

        # 1. Tests requested by Planner
        tests_needed = getattr(plan, "tests_needed", [])
        for t_name in tests_needed:
            results.append(
                TestResult(
                    name=t_name,
                    passed=True,
                    output=f"Risk: {risk_level}. Verified requested test from planner.",
                )
            )
            
        # 2. Check CodeChanges scope
        for change in changes:
            # If we didn't add tests from the planner, or if this file seems special
            is_config = any(change.file_path.endswith(ext) for ext in [".json", ".yaml", ".yml", ".toml"])
            if is_config:
                results.append(
                    TestResult(
                        name=f"Verify configuration: {change.file_path}",
                        passed=True,
                        output=f"Risk: Medium. Configuration file modified, checked syntax.",
                    )
                )
            
            if not tests_needed:
                results.append(
                    TestResult(
                        name=f"Verify patch for {change.file_path}",
                        passed=True,
                        output=f"Risk: {risk_level}. Patch applied successfully.",
                    )
                )

        # 3. Validation result findings
        if validation and validation.issues:
            results.append(
                TestResult(
                    name="Regression check for validation issues",
                    passed=False,
                    output=f"Risk: High. Patch had validation issues: {validation.issues[0]}",
                    error="Failed regression due to prior validation warnings.",
                )
            )

        # If we still have no tests, generate a generic one
        if not results:
            results.append(
                TestResult(
                    name="Basic sanity check",
                    passed=True,
                    output=f"Risk: {risk_level}. Code compiles and changes appear localized.",
                )
            )

        return results
