"""Validator agent for Sentinel Brain.

Evaluates proposed :class:`CodeChange` objects to determine whether they
are safe, sufficient, and aligned with the implementation plan.

Design:
    - The agent is a **pure LLM class** — it does not access databases,
      files, or external services directly.
    - All context (changes, plan, issue, code chunks) is passed in via
      the ``validate`` method.
    - The LLM acts as a code reviewer checking alignment and correctness.
    - Output is parsed into the existing :class:`ValidationResult` model.
    - Includes a deterministic fallback that uses heuristics when the
      LLM is unavailable.
"""

from __future__ import annotations

import json
import logging
import re
from typing import TYPE_CHECKING, Any

from forge_workflows.state import (
    CodeChange,
    Plan,
    RepoContext,
    RetrievedChunk,
    SelectedIssue,
    ValidationResult,
)

if TYPE_CHECKING:
    from langchain_core.language_models import BaseChatModel

logger = logging.getLogger(__name__)


class ValidatorAgent:
    """Evaluates code changes against the plan and issue context.

    Args:
        llm: A LangChain chat model instance (e.g. ``ChatGoogleGenerativeAI``).
    """

    name: str = "validator"

    def __init__(self, llm: BaseChatModel) -> None:
        self._llm = llm

    async def validate(
        self,
        *,
        code_changes: list[CodeChange],
        plan: Plan,
        selected_issue: SelectedIssue,
        repo_context: RepoContext,
        retrieved_chunks: list[RetrievedChunk],
    ) -> ValidationResult:
        """Validate proposed code changes.

        Args:
            code_changes: The patches generated by the DeveloperAgent.
            plan: The implementation plan the patches should follow.
            selected_issue: The issue being resolved.
            repo_context: Repository understanding from the repo_analyzer.
            retrieved_chunks: Relevant code chunks from Qdrant.

        Returns:
            A :class:`ValidationResult` with pass/fail, issues, and suggestions.
        """
        logger.info(
            "Validating %d code change(s) for issue #%d: %s",
            len(code_changes),
            selected_issue.number,
            selected_issue.title,
        )

        if not code_changes:
            logger.warning("No code changes to validate")
            return ValidationResult(
                passed=False,
                issues=["No code changes were generated by the developer."],
                suggestions=["Re-run the developer agent to generate changes."],
            )

        prompt = self._build_prompt(
            code_changes, plan, selected_issue, repo_context, retrieved_chunks
        )

        try:
            response = await self._llm.ainvoke(prompt)
            content = response.content if hasattr(response, "content") else str(response)
            parsed = self._parse_llm_response(content)
            result = self._build_validation_result(parsed)
            logger.info(
                "Validation %s (%d issues, %d suggestions)",
                "PASSED" if result.passed else "FAILED",
                len(result.issues),
                len(result.suggestions),
            )
            return result
        except Exception:
            logger.exception("LLM validation failed — using heuristic fallback")
            return self._fallback_validate(
                code_changes, plan, selected_issue, retrieved_chunks
            )

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _build_prompt(
        self,
        changes: list[CodeChange],
        plan: Plan,
        issue: SelectedIssue,
        repo_context: RepoContext,
        chunks: list[RetrievedChunk],
    ) -> str:
        """Construct the validation prompt for the LLM."""

        # Issue
        issue_block = (
            f"Issue #{issue.number}: {issue.title}\n"
            f"Body: {issue.body or '(no description)'}"
        )

        # Plan
        plan_block = (
            f"Approach: {plan.approach_reasoning}\n"
            f"Affected Files: {', '.join(plan.affected_files)}\n"
        )
        if plan.tasks:
            plan_block += "Tasks:\n"
            for t in plan.tasks:
                plan_block += f"  [{t.id}] {t.description}\n"

        # Code changes
        changes_block = ""
        for i, c in enumerate(changes, 1):
            changes_block += (
                f"  Change {i}:\n"
                f"    File: {c.file_path}\n"
                f"    Description: {c.description}\n"
                f"    Patch:\n{c.patch}\n\n"
            )

        # Retrieved chunks (original code)
        if chunks:
            context_block = ""
            for chunk in chunks:
                context_block += (
                    f"  {chunk.file_path} "
                    f"(lines {chunk.start_line}-{chunk.end_line}, {chunk.language}):\n"
                    f"  ```\n{chunk.content}\n  ```\n\n"
                )
        else:
            context_block = "  (No original code context available)\n"

        return f"""You are a senior software engineer performing a validation review of AI-generated code changes.

Your job is to determine whether the proposed changes are SAFE, SUFFICIENT, and ALIGNED with the implementation plan.

Repository: {repo_context.repository_name}
Languages: {', '.join(repo_context.languages) or 'Unknown'}

{issue_block}

Implementation Plan:
{plan_block}

Proposed Code Changes:
{changes_block}

Original Code Context:
{context_block}

Validation Criteria:
1. Does the patch address the selected issue?
2. Were only necessary files modified?
3. Did the developer follow the planner's strategy?
4. Was the retrieved code context used appropriately?
5. Were any unrelated modifications introduced?
6. Is existing functionality preserved?
7. Is the patch minimal (no unnecessary changes)?
8. Is the patch internally consistent?

Respond with a JSON object containing exactly these fields:

1. "passed": true if the changes are safe and sufficient, false otherwise.

2. "issues": A list of specific problems found. Empty list if none.
   Examples: "Modified unrelated file X", "Missing change described in task_2",
   "Contradicts planner approach".

3. "suggestions": A list of actionable recommendations.
   Examples: "Proceed to testing and review", "Consider adding a comment",
   "Re-run developer to fix task_2".

Respond with valid JSON only. No markdown, no explanation, just the JSON object."""

    @staticmethod
    def _parse_llm_response(content: str) -> dict[str, Any]:
        """Extract a JSON object from the LLM response."""
        text = content.strip()

        # Strip markdown code fences
        fence_match = re.search(r"```(?:json)?\s*\n?(.*?)```", text, re.DOTALL)
        if fence_match:
            text = fence_match.group(1).strip()

        try:
            parsed = json.loads(text)
            if isinstance(parsed, dict):
                return parsed
            logger.warning("LLM returned unexpected JSON type: %s", type(parsed))
            return {}
        except json.JSONDecodeError as exc:
            logger.warning("Failed to parse LLM JSON response: %s", exc)
            logger.debug("Raw LLM output: %s", content[:500])
            return {}

    @staticmethod
    def _build_validation_result(parsed: dict[str, Any]) -> ValidationResult:
        """Build a ValidationResult from the LLM response."""
        passed = parsed.get("passed", False)
        issues = parsed.get("issues", [])
        suggestions = parsed.get("suggestions", [])

        # Ensure types
        if not isinstance(passed, bool):
            passed = bool(passed)
        if not isinstance(issues, list):
            issues = [str(issues)]
        if not isinstance(suggestions, list):
            suggestions = [str(suggestions)]

        return ValidationResult(
            passed=passed,
            issues=[str(i) for i in issues],
            suggestions=[str(s) for s in suggestions],
        )

    @staticmethod
    def _fallback_validate(
        changes: list[CodeChange],
        plan: Plan,
        issue: SelectedIssue,
        chunks: list[RetrievedChunk],
    ) -> ValidationResult:
        """Deterministic heuristic validation when LLM is unavailable."""
        issues: list[str] = []
        suggestions: list[str] = []

        # Check 1: CodeChanges only touch planned files
        planned_files = set(plan.affected_files)
        changed_files = {c.file_path for c in changes}
        extra_files = changed_files - planned_files
        if extra_files:
            issues.append(
                f"Changes touch files not in the plan: {', '.join(sorted(extra_files))}"
            )

        # Check 2: All planned files are covered
        missing_files = planned_files - changed_files
        if missing_files:
            issues.append(
                f"Plan expected changes to: {', '.join(sorted(missing_files))}"
            )

        # Check 3: CodeChanges only touch retrieved files
        retrieved_files = {c.file_path for c in chunks}
        unverified = changed_files - retrieved_files
        if unverified:
            suggestions.append(
                f"Changes touch files not in retrieved context: "
                f"{', '.join(sorted(unverified))}. Verify manually."
            )

        # Check 4: Descriptions mention the issue
        issue_keywords = set(issue.title.lower().split())
        for change in changes:
            desc_lower = change.description.lower()
            if not any(kw in desc_lower for kw in issue_keywords if len(kw) > 3):
                suggestions.append(
                    f"Description for {change.file_path} doesn't clearly "
                    f"reference the issue: '{issue.title}'"
                )

        # Check 5: Patches are non-empty
        for change in changes:
            if len(change.patch.strip()) < 10:
                issues.append(f"Patch for {change.file_path} appears empty or trivial.")

        # Check 6: Excessive modifications
        if len(changes) > len(plan.affected_files) * 2:
            issues.append(
                f"Generated {len(changes)} changes for "
                f"{len(plan.affected_files)} planned files — seems excessive."
            )

        passed = len(issues) == 0
        if passed and not suggestions:
            suggestions.append("All heuristic checks passed. Proceed to testing and review.")

        return ValidationResult(
            passed=passed,
            issues=issues,
            suggestions=suggestions,
        )
